##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile
##

RM	= rm -rf

all	:
		make -s -C ./src/core/

clean	:
		make clean -s -C ./src/core/

fclean	:	clean
		make fclean -s -C ./src/core/

re	:
		make re -s -C ./src/core/

.PHONY	:	all clean fclean re