##
## EPITECH PROJECT, 2020
## NWP_myteams_2019
## File description:
## Makefile
##

all:
	make -C ./cli/
	make -C ./server/

clean:
	make clean -C ./cli/
	make clean -C ./server/

fclean:
	make fclean -C ./cli/
	make fclean -C ./server/

re:
	make re -C ./cli
	make re -C ./server
